config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'posts#index'
  resources :posts, only: [:show, :new, :create, :edit, :update, :destroy] do
    resources :comments, only: [:index, :new, :create, :destroy]
  end
  resources :categories, only: [:index, :new, :create, :destroy] do
    resources :category_posts, only: [:new, :create, :destroy]
  end
  get "/pages/:page" => "pages#show"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :category_posts
  has_many :posts, through: :category_posts
  validates :name, uniqueness: :true
end

app/models/category_post.rb
class CategoryPost < ApplicationRecord
  belongs_to :category
  belongs_to :post
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  validates :body, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :content, presence: true
  mount_uploader :photo, PhotoUploader

  has_many :category_posts
  has_many :categories, through: :category_posts
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :posts
  has_many :comments
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!, except: [:index, :show]
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to categories_path
    else
      render "categories/new"
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name, :category_posts_id, :id)
  end


end

app/controllers/category_posts_controller.rb
class CategoryPostsController < ApplicationController

  def new
    @category = Category.find(params[:category_id])
    @category_post = CategoryPost.new
    @posts = (Post.all - @category.posts)

    #to change pour avoir que les posts qui sont pas deja dans la categorie en question
  end

  def create
    @category = Category.find(params[:category_id])
    @category_post = @category.category_posts.new(category_post_params)
    if @category_post.save
      redirect_to categories_path
    else
      render "category_posts/new"
    end
  end



  private

  def category_post_params
    params.require(:category_post).permit(:post_id, :category_id, :id)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
skip_before_action :authenticate_user!, except: [:destroy]
  def new
    @post = Post.find(params[:post_id])
    @comment = Comment.new
    raise
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    if @comment.save
      redirect_to post_path(@post)
    else
      render 'posts/show'
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to root_path
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :pseudo, :post_id)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def show
    render template: "pages/#{params[:page]}"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all.order("created_at DESC").paginate(page: params[:page], per_page: 5)
  end

  def show
    @comment = Comment.new
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to post_path(@post)
    else
      render "posts/new"
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_path
  end

private

  def post_params
    params.require(:post).permit(:title, :content, :category_posts_id, :user_id,:photo)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/index.html.erb
<% if user_signed_in? %>

  <div class="container">
    <% @categories.each do |category| %>
      <div class="card">
        <div class="content-card">
          <strong><%= category.name %></strong>
          <br> <br>
          <%= link_to "Ajouter des posts à cette catégorie", new_category_category_post_path(category)%>
          <br>
          <br>
          <%= link_to "Supprimer cette catégorie", category_path(category), method: :delete, data: { confirm: "Are you sure ?" } %>
        </div>
        <br>
        <div class="time-card">
          <% category.posts.each do |post| %>
          <%= post.title %> <br>

          <% end %>
        </div>
      </div>
    <% end %>
    <div class="add-article">
        <%= link_to "Ajouter une catégorie", new_category_path %>
    </div>
  </div>

<%end %>

app/views/categories/new.html.erb
<div class="container">
  <%= simple_form_for(@category) do |f| %>
    <%= f.input :name, label: "Nom" %>
    <%= f.button :submit, value: 'Créer cette catégorie'%>
    <% end %>


  <%= link_to "Retour à la liste des catégories", categories_path %>
</div>

app/views/category_posts/new.html.erb
<div class="container">
  <%= @category.name %>

<%= simple_form_for([@category, @category_post]) do |f| %>
    <div class="category-form">
      <div> <%= f.association :post, required: true, label: "", collection: @posts, include_blank: "Ajouter un post" %> </div>
      <div> <%= f.submit "Ajouter", class: "btn btn-add" %> </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Leckerli+One" rel="stylesheet">
    <title>BLOG</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%#= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= render 'shared/instagramfeed' %>
  </body>
  <script>
    const photosIndex = document.querySelectorAll('.photo-index');

    function toggleOpen() {
      this.classList.toggle('photo-index-click');
    }

    photosIndex.forEach(photo => photo.addEventListener('click', toggleOpen));


  </script>
</html>

app/views/pages/about.html.erb
<div class="container">
  <div class="about-container">
    <div><h1>À PROPOS</h1> </div>
    <br>
    <div> <%= image_tag "julieabout.png", class: "img-about" %> </div>
    <br>
    <div class="text-center"> <p>
      Si vous débarquez sur mon petit blog et que vous commencez par cette rubrique, vous ne devez pas encore savoir énormément de choses sur moi. Pour résumé, mes amis m’appellent Jean-Michel bons plans, alors j’ai décidé de vous partager mes petites adresses, astuces, etc. En mars 2018, une de mes amies a décidé de se lancer dans l’aventure du wagon et pour s’entrainer à coder, elle a décidé de me créer un blog. <br> <br>
      Pour me décrire brièvement, je fais partie de ces gens qui sont souvent arrêtés par la brigade du kiff. Je vous ferai découvrir mes bonnes adresses lors de mes voyages. Je partagerai également mes bons plans food, déco, fringues sur Lille et autre contrées sympathiques. <br> <br>
      Bloguement vôtre, <br> <br>
      Julie Bis
  </p> </div>
  </div>

</div>

app/views/pages/bonsplans.html.erb
<div class="container">
  <% Post.joins(:categories).where(categories: {name: "Bons Plans"}).each do |post| %>
 <div class="card">
      <div class="time-card">
        <%= l(post.created_at,format: :long) %>
      </div>
      <div class="title-card">
        <%= post.title %>
      </div>
      <div class="content-card">
        <%= post.content.first(400) %> (...)
      </div>
      <div class="link-card">
        <%= link_to "Lire la suite", post_path(post) %>
      </div>
       <div class="photo-index">
        <%= cl_image_tag post.photo, crop: :fill%>
      </div>
    </div>
  <% end %>

</div>

app/views/pages/diy.html.erb
<div class="container">
  <% Post.joins(:categories).where(categories: {name: "DIY"}).each do |post| %>
 <div class="card">
      <div class="time-card">
        <%= l(post.created_at,format: :long) %>
      </div>
      <div class="title-card">
        <%= post.title %>
      </div>
      <div class="content-card">
        <%= post.content.first(400) %> (...)
      </div>
      <div class="link-card">
        <%= link_to "Lire la suite", post_path(post) %>
      </div>
       <div class="photo-index">
        <%= cl_image_tag post.photo, crop: :fill%>
      </div>
    </div>
  <% end %>


</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/myshop.html.erb
<div class="container">
  <% Post.joins(:categories).where(categories: {name: "My Shop"}).each do |post| %>
 <div class="card">
      <div class="time-card">
        <%= l(post.created_at,format: :long) %>
      </div>
      <div class="title-card">
        <%= post.title %>
      </div>
      <div class="content-card">
        <%= post.content.first(400) %> (...)
      </div>
      <div class="link-card">
        <%= link_to "Lire la suite", post_path(post) %>
      </div>
       <div class="photo-index">
        <%= cl_image_tag post.photo, crop: :fill%>
      </div>
    </div>
  <% end %>



</div>

app/views/pages/voyages.html.erb
<div class="container">
  <% Post.joins(:categories).where(categories: {name: "Voyages"}).each do |post| %>
 <div class="card">
      <div class="time-card">
        <%= l(post.created_at,format: :long) %>
      </div>
      <div class="title-card">
        <%= post.title %>
      </div>
      <div class="content-card">
        <%= post.content.first(400) %> (...)
      </div>
      <div class="link-card">
        <%= link_to "Lire la suite", post_path(post) %>
      </div>
       <div class="photo-index">
        <%= cl_image_tag post.photo, crop: :fill%>
      </div>
    </div>
  <% end %>



</div>

app/views/posts/edit.html.erb
<div class="container">
  <%= simple_form_for(@post) do |f| %>
    <%= f.input :title, label: "Titre" %>
    <%= f.input :content, as: :text, :input_html => { class: 'test', :cols => 5, :rows => 10 } %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
    <%= f.button :submit, value: 'Editer cet article'%>
  <% end %>

  <div class="add-article">
      <%= link_to "Retour à la liste des articles", root_path %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container">
  <% @posts.each do |post| %>
 <div class="card">
      <div class="time-card">
        <%= l(post.created_at,format: :long) %>
      </div>
      <div class="title-card">
        <%= post.title %>
      </div>
      <div class="content-card">
        <%= post.content.first(400) %> (...)
      </div>
      <div class="link-card">
        <%= link_to "Lire la suite", post_path(post) %>
      </div>
       <div class="photo-index">
        <%= cl_image_tag post.photo, crop: :fill%>
      </div>
    </div>
  <% end %>

  <div class="add-article">
    <% if user_signed_in? %>
      <%= link_to "Ajouter un article", new_post_path %>
    <%end %>
  </div>
  <div class="pagination">
  <%= will_paginate @posts, renderer: BootstrapPagination::Rails, previous_label: "Plus récent", next_label: "Suivant", inner_window: 1, outer_window: 1 %>
  </div>

</div>

app/views/posts/new.html.erb
<div class="container">
  <%= simple_form_for(@post) do |f| %>
    <%= f.input :title, label: "Titre" %>
    <%= f.input :content, as: :text, :input_html => { class: 'test', :cols => 5, :rows => 10 } %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
    <%= f.button :submit, value: 'Publier cet article'%>
    <% end %>


  <%= link_to "Retour à l'accueil", root_path %>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="row">

    <div class="card">
      <div class="time-card">
        <%= l(@post.created_at,format: :long) %>
      </div>
      <div class="title-card">
        <%= @post.title %>
      </div>
      <div class="photo-show">
        <%= cl_image_tag @post.photo, crop: :fill%>
      </div>
      <br><br>
      <div class="content-card">
        <%= @post.content %>
      </div>

      <br><br>

      <div class="review-card">
        <div id="reviews">
          <% @post.comments.each do |comment| %>
            <p> <strong> <%= comment.pseudo %> </strong> </p>
            <p> "<%= comment.body %>" </p>
            <%if user_signed_in? %>
              <%= link_to "Supprimer ce commentaire", post_comment_path(@post, comment), method: :delete, data: { confirm: "Confirmer la suppression de ce commentaire?" } %>
            <% end %>
            <br><br>
          <%end%>
        </div>

        <br><br>

        <div id="add-review">
          <p> Laisser un commentaire : </p>
          <%= simple_form_for([@post, @comment]) do |f| %>
            <%= f.input :pseudo, method: :create, label: false, placeholder: "Votre pseudo"%>
            <%= f.input :body, method: :create, label: false, placeholder: "Votre commentaire..."%>
            <%= f.button :submit, "Publier", class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>


      <div class="add-article">
        <%= link_to "Retour à la liste des articles", root_path %>
        <% if @post.user == current_user %>
          <br> <br>
          <%= link_to "Editer mon article", edit_post_path(@post) %>
          <br> <br>
          <%= link_to "Supprimer cet article", post_path(@post), method: :delete, data: { confirm: "Confirmer la suppression de cet article ?" } %>
        <% end %>
      </div>

    </div>
  </div>

</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://www.instagram.com/juliebis/", target="_blank"><i class="fab fa-instagram"></i></a>
    <a href="https://www.instagram.com/juliebis/", target="_blank"><i class="fab fa-facebook-f"></i></a>
    <a href="https://www.instagram.com/juliebis/", target="_blank"><i class="fab fa-pinterest"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fa fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/shared/_instagramfeed.html.erb
<div id="pixlee_container"></div><script type="text/javascript">window.PixleeAsyncInit = function() {Pixlee.init({apiKey:'pBJHVvudrxfYgB0hXZ8I'});Pixlee.addSimpleWidget({widgetId:'8075'});};</script><script src="//instafeed.assets.pixlee.com/assets/pixlee_widget_1_0_0.js"></script>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-fixed-top">
  <div class="navbar-logo-julie">
  <a href="/" class="navbar-wagon-brand">
    <%= image_tag "logojulie.png", class: "logo" %>
  </a>
  </div>
  <!-- Logo -->
  <div class="navbar-classic">
    <div class="navbar-logos">

      <div class="navbar-logo">
        <a href="https://www.instagram.com/juliebis/", target="_blank"><i class="fab fa-instagram"></i></a>
      </div>
      <div class="navbar-logo">
        <a href="https://www.instagram.com/juliebis/", target="_blank"><i class="fab fa-facebook-f"></i></a>
      </div>
      <div class="navbar-logo">
        <a href="https://www.instagram.com/juliebis/", target="_blank"><i class="fab fa-pinterest"></i></a>
      </div>
    </div>



    <!-- Right Navigation -->
    <div class="navbar-wagon-right hidden-xs hidden-sm">

      <div class="navbar-tabs">
        <%= link_to "BLOG", root_path, class: "navbar-wagon-item navbar-wagon-link" %>
      </div>
      <div class="navbar-tabs">
        <%= link_to "VOYAGES", "/pages/voyages" , class: "navbar-wagon-item navbar-wagon-link" %>
      </div>
      <div class="navbar-tabs">
        <%= link_to "BONS PLANS", "/pages/bonsplans", class: "navbar-wagon-item navbar-wagon-link" %>
      </div>
      <div class="navbar-tabs">
        <%= link_to "DIY", "/pages/diy", class: "navbar-wagon-item navbar-wagon-link" %>
      </div>
      <div class="navbar-tabs">
        <%= link_to "MY SHOP", "/pages/myshop", class: "navbar-wagon-item navbar-wagon-link" %>
      </div>
      <div class="navbar-tabs">
        <%= link_to "À PROPOS", "/pages/about", class: "navbar-wagon-item navbar-wagon-link" %>
      </div>

      <div class="navbar-wagon-item">
        <div class="dropdown">

          <% if user_signed_in? %>
            <%= image_tag "julie.png", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>

            <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
              <li>
                <%= link_to "#" do %>
                  <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
                <% end %>
              </li>
              <li>
                <%= link_to "#" do %>
                  <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <i class="fa fa-sign-out-alt"></i>  <%= t(".sign_out", default: "Log out") %>
                <% end %>
              </li>
              <li>
                <%= link_to categories_path do %>
                  <i class="fas fa-folder-open"> Categories </i>
                <% end %>
              </li>
            </ul>
          <% end %>
        </div>
      </div>
  </div>

    <!-- Dropdown list appearing on mobile only -->
    <div class="navbar-wagon-item hidden-md hidden-lg">
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li> <%= link_to "BLOG", root_path %> </li>
          <li><a href="/pages/voyages">VOYAGES</a></li>
          <li><a href="/pages/bonsplans">BONS PLANS</a></li>
          <li><a href="/pages/diy">DIY</a></li>
          <li><a href="/pages/myshop">MY SHOP</a></li>
          <li><a href="/pages/about">À PROPOS</a></li>
        </ul>
      </div>
    </div>
  </div>
  </div>